### ISSUE TITLE
[ts] could not find a declaration file (.d.ts)

### ISSUE THREAD

**Issue by hariomv-exzeo** [tibdex/github-cherry-pick#2]
Not able to require and use function

**Comment by tibdex** [comment]
Hi Hariom, can you please give more details?

**Comment by hariomv-exzeo** [comment]
basically, I want dts file.

**Comment by tibdex** [comment]
Well this project uses [Flow](https://flow.org/) so there is no `.d.ts` file in the npm package.

**Comment by hariomv-exzeo** [comment]
I am using expressJS with mongoose and calling your function in this way :
````
exports.cherrypick = function (req, res) {
  
  const result =  cherryPickCommits({ 
        commits: [ '0d4e1843aff9fe26f542e7069ebf44256980c235',
        '919ae1b8987e0a3c16fd574d3380552aa8290029',
        'edaea3e735f8c69c2c65028d369eea191cddd6cc' ],
        head: "master",
        octokit,
        owner: "exzeo",    
        repo: "git-automation",
      }).then(newHeadSha => {
        console.log(newHeadSha);
      });

}
```

and getting this error

```
TypeError: cherryPickCommits is not a function
    at exports.cherrypick (/home/hariomv/Documents/jira-workflow-automation/app/controllers/githubpr.controller.js:240:19)
    at Layer.handle [as handle_request] (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/layer.js:95:5)
    at /home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/index.js:281:22
    at param (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/index.js:354:14)
    at param (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/index.js:410:3)
    at next (/home/hariomv/Documents/jira-workflow-automation/node_modules/express/lib/router/index.js:275:10)
    at /home/hariomv/Documents/jira-workflow-automation/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/hariomv/Documents/jira-workflow-automation/node_modules/raw-body/index.js:224:16)
    at done (/home/hariomv/Documents/jira-workflow-automation/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/hariomv/Documents/jira-workflow-automation/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)

```

Also, I am new with NodeJS. So, plz ignore if i do some silly  mistakes.

**Comment by tibdex** [comment]
You should add a `const cherryPickCommits = require('github-cherry-pick')` in your `githubpr.controller.js` as shown in the [readme](https://github.com/tibdex/github-cherry-pick#usage).

**Comment by hariomv-exzeo** [comment]
![image](https://user-images.githubusercontent.com/40633561/45894019-d185bd80-bdea-11e8-8468-d2b2f9e512c1.png)

**Comment by tibdex** [comment]
As I said, there is no TypeScript declaration file shipped in this package so the error you're seeing in Visual Studio Code is expected. You can try what they sugggest: "add a nex declaration (.d.ts) file containing \`declare module 'github-cherry-pick';\`".

**Comment by hariomv-exzeo** [comment]
the above-mentioned suggestion didn't work. After some googling, I changed the last line of your code and function starts working!

`module.exports = cherryPickCommits;`

**Comment by tibdex** [comment]
Hi Hariom, this should be fixed now and I also switched the library to TypeScript ;).
